#!/bin/sh
################################################################################
# Copyright (c) 2014 William A. Kennington III
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
################################################################################

KEY="example-acquire-lock"

SCRIPT_DIR="$(readlink -f "$(dirname "$0")/..")"
. $SCRIPT_DIR/consul-lib.sh

clean_up() {
  while ! session_destroy "$SESSION"; do
    echo "Failed to destroy session, retrying in 1s"
    sleep 1
  done
  exit $1
}

if ! SESSION="$(session_create_persist example)"; then
  echo "Failed to get session from $HTTP_HOST"
  exit 1
fi
echo "Session ID: $SESSION"

echo "Entering lock acquire loop"
IDX=0
while ! lock acquire "$KEY" "$SESSION"; do
  IDX="$(wait_on_key "$KEY" "$IDX")"
  if [ "$?" -ne "0" ]; then
    echo "Failed to wait on key: $KEY"
    clean_up
  fi
  echo "Lock key updated"
done

echo "Acquired Lock"
echo -n "Press Enter To Exit... "
read

while ! lock release "$KEY" "$SESSION"; do
  echo "Failed to release lock, retrying in 1s"
  sleep 1
done
clean_up
